services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: productApiDB
      POSTGRES_PASSWORD: productApiPass
      POSTGRES_DB: productApiDB
    ports:
      - "5432:5432"
   
  quarkus-app:
    image: product-api-app
    build: 
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/productApiDB
      QUARKUS_DATASOURCE_USERNAME: productApiDB
      QUARKUS_DATASOURCE_PASSWORD: productApiPass
      